const practiceWordsData = {
  hiragana: [
    ["あめ", "ame", "rain / candy", "အာမဲ", "မိုး / သကြားလုံး"],
    ["いえ", "ie", "house", "အီအဲ", "အိမ်"],
    ["いぬ", "inu", "dog", "အီနု", "ခွေး"],
    ["おい", "oi", "nephew", "အိုအိ", "တူ"],
    ["おねえさん", "oneesan", "older sister", "အိုနေးဆန်", "အစ်မ"],
    ["おにいさん", "oniisan", "older brother", "အိုနီးဆန်", "အစ်ကို"],
    ["おとうと", "otouto", "younger brother", "အိုတိုးတို", "ညီ / မောင်"],
    ["おとうさん", "otousan", "father", "အိုတိုးဆန်", "အဖေ"],
    ["おかあさん", "okaasan", "mother", "အိုကားဆန်", "အမေ"],
    ["すし", "sushi", "sushi", "ဆူရှီ", "ဆူရှီ"],
    ["ねこ", "neko", "cat", "နေကို", "ကြောင်"],
    ["みず", "mizu", "water", "မိဇု", "ရေ"],
    ["がっこう", "gakkou", "school", "ဂတ်ကိုး", "ကျောင်း"],
    ["せんせい", "sensei", "teacher", "ဆန်းဆေး", "ဆရာ / ဆရာမ"],
    ["ありがとう", "arigatou", "thank you", "အာရိဂါတိုး", "ကျေးဇူးတင်ပါတယ်"],
    ["おはよう", "ohayou", "good morning", "အိုဟာယိုး", "မင်္ဂလာနံနက်ခင်းပါ"],
    ["こんばんは", "konbanwa", "good evening", "ကွန်ဘန်ဝါ", "မင်္ဂလာညချမ်းပါ"],
    ["さようなら", "sayounara", "goodbye", "ဆာယိုးနာရာ", "နှုတ်ဆက်ပါတယ် / သွားတော့မယ်နော်"],
    ["ほん", "hon", "book", "ဟွန်း", "စာအုပ်"],
    ["ぺん", "pen", "pen", "ပင်း", "ဘောပင်"],
    ["かみ", "kami", "paper", "ကာမိ", "စက္ကူ"],
    ["つくえ", "tsukue", "desk", "ဆုကုအဲ", "စာရေးစားပွဲ"],
    ["いす", "isu", "chair", "အီးစု", "ကုလားထိုင်"],
    ["ドア", "doa", "door", "ဒိုအာ", "တံခါး"],
    ["まど", "mado", "window", "မာဒို", "ပြတင်းပေါက်"],
    ["あかい", "akai", "red", "အာကိုင်း", "အနီရောင်"],
    ["あおい", "aoi", "blue", "အိုအိုင်း", "အပြာရောင်"],
    ["しろい", "shiroi", "white", "ရှီရိုင်း", "အဖြူရောင်"],
    ["くろい", "kuroi", "black", "ကုရိုင်း", "အနက်ရောင်"],
    ["ともだち", "tomodachi", "friend", "တိုမိုဒါချိ", "သူငယ်ချင်း"],
    ["くるま", "kuruma", "car", "ကုရုမာ", "ကား"],
    ["さくら", "sakura", "cherry blossom", "ဆာကူရာ", "ချယ်ရီပန်း"],
    ["てんき", "tenki", "weather", "တန်းကိ", "ရာသီဥတု"],
    ["でんしゃ", "densha", "train", "ဒန်းရှာ", "ရထား"],
    ["かぞく", "kazoku", "family", "ကာဇိုကု", "မိသားစု"],
    ["くに", "kuni", "country", "ကူနိ", "နိုင်ငံ"],
    ["おちゃ", "ocha", "green tea", "အိုချာ", "ရေနွေးကြမ်း / လက်ဖက်ရည်စိမ်း"],
    ["ごはん", "gohan", "rice / meal", "ဂိုဟန်", "ထမင်း / အစားအစာ"],
    ["くだもの", "kudamono", "fruit", "ကုဒါမိုနို", "သစ်သီး"],
    ["やさい", "yasai", "vegetables", "ယာဆိုင်း", "ဟင်းသီးဟင်းရွက်"],
    ["にく", "niku", "meat", "နိကု", "အသား"],
    ["さかな", "sakana", "fish", "ဆာကာနာ", "ငါး"],
    ["たまご", "tamago", "egg", "တာမာဂို", "ကြက်ဥ / ဘဲဥ"],
    ["かいもの", "kaimono", "shopping", "ကိုင်းမိုနို", "ဈေးဝယ်ခြင်း"],
    ["はな", "hana", "flower", "ဟာနာ", "ပန်း"],
    ["とり", "tori", "bird", "တိုရိ", "ငှက်"],
    ["やま", "yama", "mountain", "ယာမာ", "တောင်"],
    ["かわ", "kawa", "river", "ကာဝါ", "မြစ်"],
    ["うみ", "umi", "sea", "အူမိ", "ပင်လယ်"],
    ["そら", "sora", "sky", "ဆိုရာ", "ကောင်းကင်"],
    ["ゆき", "yuki", "snow", "ယုကိ", "နှင်း"],
    ["かぜ", "kaze", "wind", "ကာဇဲ", "လေ"],
    ["あさ", "asa", "morning", "အာဆာ", "မနက်ခင်း"],
    ["ひる", "hiru", "afternoon", "ဟီရု", "နေ့လယ်"],
    ["よる", "yoru", "night", "ယောရု", "ည"],
    ["きょう", "kyou", "today", "ကျိုး", "ယနေ့"],
    ["あした", "ashita", "tomorrow", "အာရှိတာ", "မနက်ဖြန်"],
    ["きのう", "kinou", "yesterday", "ကီနိုး", "မနေ့က"],
    ["じかん", "jikan", "time", "ဂျိကန်", "အချိန်"]
  ],
  katakana: [
    ["コーヒー", "koohii", "coffee", "ကိုးဟီး", "ကော်ဖီ"],
    ["ホテル", "hoteru", "hotel", "ဟိုတဲရု", "ဟိုတယ်"],
    ["バス", "basu", "bus", "ဘာစု", "ဘတ်စ်ကား"],
    ["テレビ", "terebi", "TV", "တဲရဲဘိ", "တီဗီ"],
    ["スマホ", "sumaho", "smartphone", "ဆုမာဟို", "စမတ်ဖုန်း"],
    ["コンビニ", "konbini", "convenience store", "ကွန်ဘိနိ", "ကုန်စုံဆိုင် / ၂၄ နာရီဆိုင်"],
    ["ファイル", "fairu", "file", "ဖိုင်ရု", "ဖိုင်"],
    ["パーティー", "paatii", "party", "ပါတီး", "ပါတီ"],
    ["ビール", "biiru", "beer", "ဘီးရု", "ဘီယာ"],
    ["ワイン", "wain", "wine", "ဝိုင်း", "ဝိုင်"],
    ["パン", "pan", "bread", "ပန်း", "ပေါင်မုန့်"],
    ["アメリカ", "amerika", "America", "အာမဲရိကာ", "အမေရိက"],
    ["イギリス", "igirisu", "England", "အီဂိရိစု", "အင်္ဂလန်"],
    ["フランス", "furansu", "France", "ဖုရန်စု", "ပြင်သစ်"],
    ["カナダ", "kanada", "Canada", "ကာနာဒါ", "ကနေဒါ"],
    ["オーストラリア", "osutorararia", "Australia", "အိုဆုတိုရာရိယာ", "ဩစတြေးလျ"]
  ]
};

const kanaMnemonics = {
  // Hiragana
  "あ": { en: "A for Apple: looks like an apple with a stem.", my: "Apple (ပန်းသီး) ပုံစံနှင့် တူသည်။", hintEn: "Apple", hintMy: "ပန်းသီး" },
  "い": { en: "Two individual eels swimming side-by-side.", my: "ငါးရှဉ့်နှစ်ကောင် ရေကူးနေသည့်ပုံစံ ဖြစ်သည်။", hintEn: "Eels", hintMy: "ငါးရှဉ့်" },
  "う": { en: "Looks like an old man bent over saying 'Ugh!'", my: "ခါးကုန်းနေသော အဘိုးအိုတစ်ဦးနှင့် တူသည်။", hintEn: "Ugh!", hintMy: "ခါးကုန်း" },
  "え": { en: "Looks like an exotic bird on a branch.", my: "ထူးဆန်းသော ငှက်တစ်ကောင်နှင့် တူသည်။", hintEn: "Bird", hintMy: "ငှက်" },
  "お": { en: "A golfer putting a ball onto the green.", my: "ဂေါက်သီးရိုက်နေသည့် ပုံစံနှင့် တူသည်။", hintEn: "Golf", hintMy: "ဂေါက်သီး" },
  "か": { en: "A kayak paddler paddling hard.", my: "လှေလှော်နေသူတစ်ဦး၏ ပုံစံနှင့် တူသည်။", hintEn: "Kayak", hintMy: "လှေ" },
  "き": { en: "Looks like a key to unlock a door.", my: "သော့တစ်ချောင်း၏ ပုံစံနှင့် တူသည်။", hintEn: "Key", hintMy: "သော့" },
  "く": { en: "Looks like the open beak of a coocoo bird.", my: "ငှက်ကလေးနှုတ်သီး ဖွင့်ထားသည့် ပုံစံနှင့် တူသည်။", hintEn: "Beak", hintMy: "နှုတ်သီး" },
  "け": { en: "Looks like a keg of beer with a tap.", my: "ဘီယာစည်ပိုင်းပုံစံနှင့် တူသည်။", hintEn: "Keg", hintMy: "စည်ပိုင်း" },
  "こ": { en: "Two cozy worms curled up.", my: "တီကောင်နှစ်ကောင် ခွေနေသည့် ပုံစံနှင့် တူသည်။", hintEn: "Cozy", hintMy: "တီကောင်" },
  "さ": { en: "A sad face tilting to the side.", my: "စောင်းနေသော မျက်နှာပုံစံနှင့် တူသည်။", hintEn: "Sad", hintMy: "မျက်နှာ" },
  "し": { en: "A shepherd's crook or fish hook.", my: "ငါးမျှားချိတ်ပုံစံနှင့် တူသည်။", hintEn: "Hook", hintMy: "ချိတ်" },
  "す": { en: "A super loop on a playground swing.", my: "ကစားကွင်းမှ ဒန်းကွင်းပုံစံနှင့် တူသည်။", hintEn: "Loop", hintMy: "ဒန်း" },
  "せ": { en: "Looks like a seat or bench.", my: "ခုံတန်းလျားပုံစံနှင့် တူသည်။", hintEn: "Seat", hintMy: "ခုံတန်း" },
  "そ": { en: "A sewing needle sewing zigzag.", my: "အပ်ချုပ်အပ်ဖြင့် ဇစ်ဇတ်ချုပ်နေသည့် ပုံစံနှင့် တူသည်။", hintEn: "Sewing", hintMy: "ဇစ်ဇတ်" },
  "た": { en: "Looks like the letters T and A.", my: "အင်္ဂလိပ်အက္ခရာ T နှင့် A ပေါင်းစပ်ပုံစံနှင့် တူသည်။", hintEn: "T & A", hintMy: "T&A" },
  "ち": { en: "A cheerleader jumping up.", my: "ခုန်ပျံနေသော အားပေးသူတစ်ဦး၏ ပုံစံနှင့် တူသည်။", hintEn: "Cheer", hintMy: "ကခုန်" },
  "つ": { en: "A big tsunami wave.", my: "ဆူနာမီလှိုင်းလုံးကြီးပုံစံနှင့် တူသည်။", hintEn: "Tsunami", hintMy: "လှိုင်း" },
  "て": { en: "Looks like a telephone pole hook.", my: "တယ်လီဖုန်းတိုင်ပုံစံနှင့် တူသည်။", hintEn: "Pole", hintMy: "ဖုန်းတိုင်" },
  "と": { en: "A torn toe with a splinter in it.", my: "ခြေချောင်းလေးထဲသို့ ဆူးစိုက်နေသည့် ပုံစံနှင့် တူသည်။", hintEn: "Toe", hintMy: "ခြေချောင်း" },
  "な": { en: "A nun praying at a cross.", my: "လက်ဝါးကပ်တိုင်ရှေ့တွင် ဆုတောင်းနေသည့် ပုံစံနှင့် တူသည်။", hintEn: "Nun", hintMy: "ဆုတောင်း" },
  "に": { en: "Two needles next to a thread.", my: "အပ်နှစ်ချောင်းနှင့် အပ်ချည်ကြိုးပုံစံနှင့် တူသည်။", hintEn: "Needles", hintMy: "အပ်" },
  "ぬ": { en: "A bowl of noodles with chopsticks.", my: "ခေါက်ဆွဲပန်းကန်နှင့် တူသည်။", hintEn: "Noodle", hintMy: "ခေါက်ဆွဲ" },
  "ね": { en: "A nest with a small bird in it.", my: "ငှက်သိုက်ပုံစံနှင့် တူသည်။", hintEn: "Nest", hintMy: "ငှက်သိုက်" },
  "の": { en: "A no entry sign.", my: "'မဝင်ရ' တားမြစ်ချက် ဆိုင်းဘုတ်နှင့် တူသည်။", hintEn: "No Entry", hintMy: "မဝင်ရ" },
  "は": { en: "Looks like the letter H and a.", my: "အင်္ဂလိပ်အက္ခရာ H နှင့် a ပုံစံနှင့် တူသည်။", hintEn: "H & a", hintMy: "H&a" },
  "ひ": { en: "A smiling he-he mouth.", my: "ရယ်မောနေသော ပါးစပ်ပုံစံနှင့် တူသည်။", hintEn: "He-He", hintMy: "ပါးစပ်" },
  "ふ": { en: "A funny nose with two nostrils.", my: "လူနှာခေါင်းပုံစံနှင့် တူသည်။", hintEn: "Nose", hintMy: "နှာခေါင်း" },
  "へ": { en: "A heavenly mountain peak.", my: "တောင်ထိပ်ပုံစံနှင့် တူသည်။", hintEn: "Peak", hintMy: "တောင်ထိပ်" },
  "ほ": { en: "A hot stove with a chimney.", my: "မီးဖိုပုံစံနှင့် တူသည်။", hintEn: "Stove", hintMy: "မီးဖို" },
  "ま": { en: "A mast on a sailing ship.", my: "ရွက်လှေ၏ ရွက်တိုင်ပုံစံနှင့် တူသည်။", hintEn: "Mast", hintMy: "ရွက်တိုင်" },
  "み": { en: "Looks like the number 21.", my: "ကိန်းဂဏန်း ၂၁ နှင့် တူသည်။", hintEn: "21", hintMy: "၂၁" },
  "む": { en: "A mooing cow head.", my: "နွားခေါင်းပုံစံနှင့် တူသည်။", hintEn: "Cow", hintMy: "နွားခေါင်း" },
  "め": { en: "Noodles but messier (no loop).", my: "ခေါက်ဆွဲဖတ်များ ရှုပ်ထွေးနေသည့် ပုံစံနှင့် တူသည်။", hintEn: "Messy", hintMy: "ရှုပ်ထွေး" },
  "も": { en: "More fishhooks (two hooks).", my: "ငါးမျှားချိတ်နှစ်ခု ပေါင်းထားသည့် ပုံစံနှင့် တူသည်။", hintEn: "More Hooks", hintMy: "ချိတ်များ" },
  "や": { en: "A yak with horns.", my: "ချိုရှည်သော နွားသိုးတစ်ကောင်၏ ပုံစံနှင့် တူသည်။", hintEn: "Yak", hintMy: "နွားသိုး" },
  "ゆ": { en: "A unique golden fish.", my: "ရွှေငါးတစ်ကောင် ကူးခတ်နေသည့် ပုံစံနှင့် တူသည်။", hintEn: "Fish", hintMy: "ရွှေငါး" },
  "よ": { en: "A yo-yo spinning around.", my: "ရိုရိုကစားစရာပုံစံနှင့် တူသည်။", hintEn: "Yo-Yo", hintMy: "ရိုရို" },
  "ら": { en: "A rabbit's ears popping up.", my: "ယုန်နားရွက်ပုံစံနှင့် တူသည်။", hintEn: "Rabbit", hintMy: "ယုန်" },
  "り": { en: "Two river streams flowing.", my: "မြစ်ချောင်းနှစ်ခု စီးဆင်းနေသည့် ပုံစံและ တူသည်။", hintEn: "River", hintMy: "မြစ်ချောင်း" },
  "る": { en: "A route with a loop at the end.", my: "အဝိုင်းပတ်ပါသော လမ်းပုံစံနှင့် တူသည်။", hintEn: "Loop Road", hintMy: "လမ်းဝိုင်း" },
  "れ": { en: "A person resting against a wall.", my: "နံရံကို မှီ၍ အနားယူနေသူနှင့် တူသည်။", hintEn: "Resting", hintMy: "အနားယူ" },
  "ろ": { en: "A road without a loop.", my: "အဝိုင်းပတ်မပါသော လမ်းပုံစံနှင့် တူသည်။", hintEn: "Road", hintMy: "လမ်း" },
  "わ": { en: "A wasp flying away.", my: "နကျယ်ကောင်တစ်ကောင် ပျံသန်းနေသည့် ပုံစံနှင့် တူသည်။", hintEn: "Wasp", hintMy: "နကျယ်" },
  "を": { en: "A worker pushing a heavy box.", my: "သေတ္တာတွန်းနေသော အလုပ်သမားတစ်ဦးနှင့် တူသည်။", hintEn: "Worker", hintMy: "အလုပ်သမား" },
  "ん": { en: "Looks like the script letter n.", my: "အင်္ဂလိပ်အက္ခရာ n အရေးအသားနှင့် တူသည်။", hintEn: "n", hintMy: "n" },

  // Katakana
  "ア": { en: "Looks like an angle pointing down.", my: "ထောင့်ပုံစံနှင့် တူသည်။", hintEn: "Angle", hintMy: "ထောင့်" },
  "イ": { en: "An easel holding a painting.", my: "ပန်းချီကားတင်သည့် စင်နှင့် တူသည်။", hintEn: "Easel", hintMy: "စင်" },
  "ウ": { en: "An umbrella frame with a point.", my: "ထီးတစ်ချောင်း၏ ထိပ်ချွန်ပုံစံနှင့် တူသည်။", hintEn: "Umbrella", hintMy: "ထီး" },
  "エ": { en: "An engineering beam.", my: "အင်ဂျင်နီယာသုံး သံတောင်ပံတိုင်နှင့် တူသည်။", hintEn: "Beam", hintMy: "သံတိုင်" },
  "オ": { en: "An overhead crane lifting a beam.", my: "မိုးပျံကရိန်းပုံစံနှင့် တူသည်။", hintEn: "Crane", hintMy: "ကရိန်း" },
  "カ": { en: "Looks like Hiragana か but sharper.", my: "ဟိရဂန か ပုံစံနှင့်တူသော်လည်း ပိုမိုချွန်ထက်သည်။", hintEn: "Ka", hintMy: "ကာ" },
  "キ": { en: "A key with straight lines.", my: "သော့ပုံစံ အတန်းဖြောင့်များနှင့် တူသည်။", hintEn: "Key", hintMy: "သော့" },
  "ク": { en: "A cook's hat.", my: "စားဖိုမှူးဦးထုပ်ပုံစံနှင့် တူသည်။", hintEn: "Cook Hat", hintMy: "ဦးထုပ်" },
  "ケ": { en: "A kettle boiling water.", my: "ရေနွေးအိုးပုံစံနှင့် တူသည်။", hintEn: "Kettle", hintMy: "ရေနွေးအိုး" },
  "コ": { en: "A corner of a box.", my: "သေတ္တာထောင့်ပုံစံနှင့် တူသည်။", hintEn: "Corner", hintMy: "ထောင့်စွန်း" },
  "サ": { en: "A cactus sticking up in the sand.", my: "ရှားစောင်းပင်ပုံစံနှင့် တူသည်။", hintEn: "Cactus", hintMy: "ရှားစောင်း" },
  "シ": { en: "She (tsunami wave from side) or looking up.", my: "လှိုင်းလုံးတစ်ခုနှင့် တူသည်။", hintEn: "She", hintMy: "မမ" },
  "ス": { en: "A hanger hook or slide.", my: "ချိတ်ဆွဲစင်ပုံစံနှင့် တူသည်။", hintEn: "Hanger", hintMy: "ချိတ်စင်" },
  "セ": { en: "Looks like Hiragana せ but simpler.", my: "ဟိရဂန せ ပုံစံနှင့်တူသော်လည်း ပိုရိုးရှင်းသည်။", hintEn: "Se", hintMy: "ဆယ်" },
  "ソ": { en: "A needle sewing downwards.", my: "အပ်တစ်ချောင်း အောက်သို့ဆွဲချနေပုံစံနှင့် တူသည်။", hintEn: "Needle", hintMy: "အပ်" },
  "タ": { en: "A tidal wave crashing.", my: "ရေလှိုင်းကြီးနှင့် တူသည်။", hintEn: "Tidal", hintMy: "လှိုင်း" },
  "チ": { en: "A cheetah running fast.", my: "ပြေးလွှားနေသော ကျားသစ်တစ်ကောင်နှင့် တူသည်။", hintEn: "Cheetah", hintMy: "ကျားသစ်" },
  "ツ": { en: "Two needles pointing down.", my: "အပ်နှစ်ချောင်း အောက်သို့ဦးတည်နေပုံစံနှင့် တူသည်။", hintEn: "Needles", hintMy: "အပ်များ" },
  "テ": { en: "A television antenna.", my: "တီဗီ အင်တင်နာပုံစံနှင့် တူသည်။", hintEn: "Antenna", hintMy: "အင်တင်နာ" },
  "ト": { en: "A totem pole.", my: "ယဉ်ကျေးမှုတိုင်ပုံစံနှင့် တူသည်။", hintEn: "Totem", hintMy: "တိုင်" },
  "ナ": { en: "A knife dagger.", my: "ဓားမြှောင်ပုံစံနှင့် တူသည်။", hintEn: "Knife", hintMy: "ဓားမြှောင်" },
  "ニ": { en: "Two needles lying flat.", my: "အပ်နှစ်ချောင်း အပြိုင်လှဲလျောင်းနေသည့် ပုံစံနှင့် တူသည်။", hintEn: "Two", hintMy: "နှစ်ခု" },
  "ヌ": { en: "Noodles being grabbed.", my: "ခေါက်ဆွဲဖတ်များကို ညှပ်ယူနေသည့် ပုံစံနှင့် တူသည်။", hintEn: "Noodle", hintMy: "ခေါက်ဆွဲ" },
  "ネ": { en: "A nest hanging on a branch.", my: "သစ်ကိုင်းတွင် တွဲလွဲခိုနေသော ငှက်သိုက်နှင့် တူသည်။", hintEn: "Nest", hintMy: "သိုက်" },
  "ノ": { en: "A nose profile line.", my: "နှာခေါင်းစောင်းပုံစံနှင့် တူသည်။", hintEn: "Nose", hintMy: "နှာခေါင်း" },
  "ハ": { en: "A hat or helmet.", my: "ဦးထုပ်ပုံစံနှင့် တူသည်။", hintEn: "Hat", hintMy: "ဦးထုပ်" },
  "ヒ": { en: "A heel of a shoe.", my: "ဖိနပ်ဖနောင့်ပုံစံနှင့် တူသည်။", hintEn: "Heel", hintMy: "ဖနောင့်" },
  "フ": { en: "A flag waving.", my: "အလံလွင့်ထူနေသည့် ပုံစံနှင့် တူသည်။", hintEn: "Flag", hintMy: "အလံ" },
  "ヘ": { en: "A peak of a mountain.", my: "တောင်ထိပ်ပုံစံနှင့် တူသည်။", hintEn: "Peak", hintMy: "တောင်ထိပ်" },
  "ホ": { en: "A holy cross.", my: "သန့်ရှင်းသော လက်ဝါးကပ်တိုင်နှင့် တူသည်။", hintEn: "Cross", hintMy: "ကပ်တိုင်" },
  "マ": { en: "A map folded.", my: "ခေါက်ထားသော မြေပုံနှင့် တူသည်။", hintEn: "Map", hintMy: "မြေပုံ" },
  "ミ": { en: "Three river streams flowing down.", my: "မြစ်ရေစီးကြောင်း သုံးခုပုံစံနှင့် တူသည်။", hintEn: "Streams", hintMy: "ချောင်းများ" },
  "ム": { en: "A moose horn.", my: "မုစ်သမင်ချိုပုံစံနှင့် တူသည်။", hintEn: "Moose", hintMy: "ချို" },
  "メ": { en: "A memo card edge.", my: "မှတ်စုကတ်၏ အစွန်းပုံစံနှင့် တူသည်။", hintEn: "Memo", hintMy: "မှတ်စု" },
  "モ": { en: "Looks like Hiragana も but simpler.", my: "ဟိရဂန も ပုံစံနှင့်တူသော်လည်း ပိုရိုးရှင်းသည်။", hintEn: "Mo", hintMy: "မို" },
  "ヤ": { en: "Looks like Hiragana や but simpler.", my: "ဟိရဂန や ပုံစံနှင့်တူသော်လည်း ပိုရိုးရှင်းသည်။", hintEn: "Ya", hintMy: "ယာ" },
  "ユ": { en: "A unique crane hook.", my: "ဆွဲချိတ်ပုံစံနှင့် တူသည်။", hintEn: "Hook", hintMy: "ချိတ်" },
  "ヨ": { en: "A yoga mat rolled out.", my: "ယောဂဖျာပုံစံနှင့် တူသည်။", hintEn: "Yoga", hintMy: "ယောဂ" },
  "ラ": { en: "A rabbit jumping.", my: "ခုန်ပျံနေသော ယုန်တစ်ကောင်နှင့် တူသည်။", hintEn: "Rabbit", hintMy: "ယုန်" },
  "リ": { en: "Two river streams flowing straight.", my: "မြစ်နှစ်စင်း ဖြောင့်တန်းစွာ စီးဆင်းပုံနှင့် တူသည်။", hintEn: "River", hintMy: "မြစ်" },
  "ル": { en: "A route or road split.", my: "လမ်းခွဲနှစ်ခုပုံစံနှင့် တူသည်။", hintEn: "Split", hintMy: "လမ်းခွဲ" },
  "レ": { en: "A ray of light reflecting.", my: "အလင်းတန်း ရောင်ပြန်ဟပ်ပုံစံနှင့် တူသည်။", hintEn: "Ray", hintMy: "ရောင်ခြည်" },
  "ロ": { en: "A robot's mouth box.", my: "စက်ရုပ်ပါးစပ် သေတ္တာပုံစံနှင့် တူသည်။", hintEn: "Box", hintMy: "သေတ္တာ" },
  "ワ": { en: "A wine glass outline.", my: "ဝိုင်ခွက်ပုံစံနှင့် တူသည်။", hintEn: "Glass", hintMy: "ဖန်ခွက်" },
  "ヲ": { en: "A worker digging.", my: "မြေတူးနေသော အလုပ်သမားတစ်ဦးနှင့် တူသည်။", hintEn: "Worker", hintMy: "အလုပ်သမား" },
  "ン": { en: "Looking down (smiling eye).", my: "မျက်လုံးတစ်ဖက် မှိတ်ပြနေသည့် ပုံစံနှင့် တူသည်။", hintEn: "Smile", hintMy: "အပြုံး" }
};

window.kanaMnemonics = kanaMnemonics;
